services:
  - type: web
    name: cs-quest-game
    env: node
    region: singapore
    buildCommand: cd cs-quest/server && npm install
    startCommand: cd cs-quest/server && node server.js
    envVars:
      - key: PORT
        value: 3000
    healthCheckPath: /api/stats
